MoedaCrypto/Models/ErrorViewModel.cs
using System;

namespace MoedaCrypto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MoedaCrypto/Models/Moedas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MoedaCrypto.Models
{
    public class Moedas
    {
        public int MoedasId { get; set; }

        public string Nome { get; set; }
        public int Quantidade { get; set; }

        [NotMapped]
        public bool CheckBoxMarcado { get; set; }
    }
}

MoedaCrypto/Models/MoedasContexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoedaCrypto.Models
{
    public class MoedasContexto : DbContext
    {
        public DbSet<Moedas>Moedas { get; set; }

        public MoedasContexto(DbContextOptions<MoedasContexto>opcoes) : base(opcoes)
        {

        }
        
    }
}

MoedaCrypto/Controllers/MoedasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoedaCrypto.Models;

namespace MoedaCrypto.Controllers
{
    public class MoedasController : Controller
    {
        private readonly MoedasContexto _context;

        public MoedasController(MoedasContexto context)
        {
            _context = context;
        }

        // GET: Moedas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Moedas.ToListAsync());
        }

        public async Task<IActionResult> EscolhadeMoedas(List<Moedas> moedas)
        {
            foreach (var item in moedas)
            {
                if (item.CheckBoxMarcado == true)
                {
                    Moedas moeda = await _context.Moedas.FirstAsync(x => x.MoedasId == item.MoedasId);
                    moeda.Quantidade += 1;
                    _context.Update(moeda);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        
        public JsonResult DadosGrafico()
        {
            return Json(_context.Moedas.Select(x => new { x.Nome, x.Quantidade }));
        }

        // GET: Moedas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Moedas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MoedasId,Nome,Quantidade")] Moedas moedas)
        {
            if (ModelState.IsValid)
            {
                moedas.Quantidade = 0;
                _context.Add(moedas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(moedas);
        }

        

       

        private bool MoedasExists(int id)
        {
            return _context.Moedas.Any(e => e.MoedasId == id);
        }
    }
}

MoedaCrypto/ViewComponents/MoedasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MoedaCrypto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MoedaCrypto.ViewComponents
{
    public class MoedasViewComponent : ViewComponent
    {
        private readonly MoedasContexto _moedasContexto;

        public MoedasViewComponent(MoedasContexto moedasContexto)
        {
            _moedasContexto = moedasContexto;
        }
        public async Task<IViewComponentResult> InvokeAsync()
            {
            //utilização de metodo para passar os dados para a view
            return View(await _moedasContexto.Moedas.ToListAsync());

            }
    }
}

MoedaCrypto/Views/Moedas/Create.cshtml
@model MoedaCrypto.Models.Moedas

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Moedas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoedaCrypto/Views/Moedas/Index.cshtml
@model IEnumerable<MoedaCrypto.Models.Moedas>

@{
    ViewData["Title"] = "Index";
}

<br />

<p>
    <a asp-action="Create" class="btn btn-primary">Nova Moeda</a>
</p>

<div class="container-fluid d-flex flex-wrap">
    <div class="col-lg-6" >
        @await Component.InvokeAsync("Moedas");
    </div>

    <div class="col-lg-6 w-25">
        <partial name="_Grafico" />
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>

<script>
    function PegarMoedas(dados) {
        var quantidade = 0;
        var moedas = [];

        while (quantidade < dados.length) {
            moedas.push(dados[quantidade].nome);
            quantidade++;

        }
        return moedas;
    }
    function PegarQuantidades(dados) {
        var quantidade = 0;
        var valores = [];

        while (quantidade < dados.length) {
            valores.push(dados[quantidade].quantidade);
            quantidade++;
        }
        return valores;
    }
    function PegarCores(quantidade) {
        var cores = [];

        while (quantidade > 0) {
            var r = Math.floor(Math.random() * 255);
            var g = Math.floor(Math.random() * 255);
            var b = Math.floor(Math.random() * 255);
            cores.push("rgb(" + r + ", " + g + "," + b + ")");
            quantidade--;
        }
        return cores;
    }
    $.ajax({
        type: "GET",
        url: "Moedas/DadosGrafico",
        success: function (dados) {

            new Chart(document.getElementById("grafico"), {
                type: 'pie',
                data: {
                    labels: PegarMoedas(dados),
                    datasets: [{
                        labels: "Quantidade",
                        borderWidth: 2,
                        backgroundColor: PegarCores(dados.length),
                        data: PegarQuantidades(dados)
                    }]
                },
                options: {
                    title: {
                        display: true,
                        text: "Quantidade em cada moeda"
                    }
                }
            });
        }

    })
</script>

MoedaCrypto/Views/Moedas/_Grafico.cshtml
<canvas id="grafico">

</canvas>

MoedaCrypto/Views/Shared/Components/Moedas/Default.cshtml
@model IList<MoedaCrypto.Models.Moedas>



<h4>Em qual moeda você investe?</h4>

<form asp-controller="Moedas" asp-action="EscolhadeMoedas" method="post" class="form-group">
    @{
        for (int i = 0; i < Model.Count(); i++)
        {
            <input asp-for="@Model[i].CheckBoxMarcado" type="checkbox" />
            <label asp-for="@Model[i].MoedasId">@Model[i].Nome</label>
            <input asp-for="@Model[i].MoedasId" type="hidden" />
            <input asp-for="@Model[i].Nome" type="hidden" />
            <br />
        } 
        <input type ="submit" value="Enviar" class="btn-primary" />
     }
</form>

MoedaCrypto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoedaCrypto</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/Chart.js/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.0/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Moedas" asp-action="Index">Crypto moedas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MoedaCrypto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/Chart.js/Chart.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.0/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>